server:
  port: 8081
  servlet:
    context-path: /psi2023

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psi20231101?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true        
    username: root
    password: 1111
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
    
